using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using OrganizationManagement.WebUI.Extensions;
using OrganizationManagement.WebUI.Models.Entities;
using OrganizationManagement.WebUI.Models.Enums;
using OrganizationManagement.WebUI.Persistence;

namespace OrganizationManagement.WebUI.HostedService
{
    public class StartupHostedService : IHostedService
    {
        private readonly IDbContextFactory<ApplicationDbContext> _dbContextFactory;

        public StartupHostedService(IDbContextFactory<ApplicationDbContext> dbContextFactory)
        {
            _dbContextFactory = dbContextFactory;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            using var context = await _dbContextFactory.CreateDbContextAsync(cancellationToken);
            await context.Database.EnsureDeletedAsync(cancellationToken);
            await context.Database.EnsureCreatedAsync(cancellationToken);
            var unitTypes = new[]
            {
                new UnitType { Id = 1, Name = "Company", Level = 1 },
                new UnitType { Id = 2, Name = "Directorate", Level = 2 },
                new UnitType { Id = 3, Name = "Division", Level = 3 },
                new UnitType { Id = 4, Name = "Department", Level = 4 },
                new UnitType { Id = 5, Name = "Section", Level = 5 },
            };
            var organizationUnits = new[]
            {
                new OrganizationUnit { Id = 1, Name = "Company", UnitTypeId = 1 },
                new OrganizationUnit { Id = 2, ParentId = 1, Name = "Marketing", UnitTypeId = 2 },
                new OrganizationUnit { Id = 3, ParentId = 1, Name = "Finance & Logistic", UnitTypeId = 2 },
                new OrganizationUnit { Id = 4, ParentId = 2, Name = "Human Resources & General Affairs", UnitTypeId = 3 },
                new OrganizationUnit { Id = 5, ParentId = 2, Name = "Information System", UnitTypeId = 3 },
                new OrganizationUnit { Id = 6, ParentId = 3, Name = "After Sales Business", UnitTypeId = 3 },
                new OrganizationUnit { Id = 7, ParentId = 3, Name = "Finance", UnitTypeId = 3 },
                new OrganizationUnit { Id = 8, ParentId = 3, Name = "Fleet Management", UnitTypeId = 3 },
                new OrganizationUnit { Id = 9, ParentId = 4, Name = "HR Operation", UnitTypeId = 4 },
                new OrganizationUnit { Id = 10, ParentId = 4, Name = "General Affairs", UnitTypeId = 4 },
                new OrganizationUnit { Id = 11, ParentId = 4, Name = "HR Method", UnitTypeId = 4 },
                new OrganizationUnit { Id = 12, ParentId = 5, Name = "System Development", UnitTypeId = 4 },
                new OrganizationUnit { Id = 13, ParentId = 5, Name = "System Operation", UnitTypeId = 4 },
                new OrganizationUnit { Id = 14, ParentId = 6, Name = "After Sales", UnitTypeId = 4 },
                new OrganizationUnit { Id = 15, ParentId = 7, Name = "Invoice", UnitTypeId = 4 },
                new OrganizationUnit { Id = 16, ParentId = 7, Name = "Incoming & Outgoing Payment", UnitTypeId = 4 },
                new OrganizationUnit { Id = 17, ParentId = 8, Name = "Fleet Area 1", UnitTypeId = 4 },
                new OrganizationUnit { Id = 18, ParentId = 8, Name = "Fleet Area 2", UnitTypeId = 4 },
                new OrganizationUnit { Id = 19, ParentId = 9, Name = "HR Business Partner", UnitTypeId = 5 },
                new OrganizationUnit { Id = 20, ParentId = 9, Name = "HR Relations", UnitTypeId = 5 },
                new OrganizationUnit { Id = 21, ParentId = 9, Name = "HR Training & Development", UnitTypeId = 5 },
                new OrganizationUnit { Id = 22, ParentId = 9, Name = "HR Recruitment", UnitTypeId = 5 },
                new OrganizationUnit { Id = 23, ParentId = 10, Name = "General Service", UnitTypeId = 5 },
                new OrganizationUnit { Id = 24, ParentId = 10, Name = "GA Planning", UnitTypeId = 5 },
                new OrganizationUnit { Id = 25, ParentId = 11, Name = "HR Information System", UnitTypeId = 5 },
                new OrganizationUnit { Id = 26, ParentId = 11, Name = "HR Organization", UnitTypeId = 5 },
                new OrganizationUnit { Id = 27, ParentId = 12, Name = "Application & Project Management", UnitTypeId = 5 },
                new OrganizationUnit { Id = 28, ParentId = 13, Name = "Infrastructure", UnitTypeId = 5 },
                new OrganizationUnit { Id = 29, ParentId = 13, Name = "Operation", UnitTypeId = 5 },
                new OrganizationUnit { Id = 30, ParentId = 14, Name = "Parts Business", UnitTypeId = 5 },
                new OrganizationUnit { Id = 31, ParentId = 14, Name = "Customer Service", UnitTypeId = 5 },
                new OrganizationUnit { Id = 32, ParentId = 15, Name = "Invoice for Area 1", UnitTypeId = 5 },
                new OrganizationUnit { Id = 33, ParentId = 15, Name = "Invoice for Area 2", UnitTypeId = 5 },
                new OrganizationUnit { Id = 34, ParentId = 16, Name = "Incoming & Outgoing Payment for Area 1", UnitTypeId = 5 },
                new OrganizationUnit { Id = 35, ParentId = 16, Name = "Incoming & Outgoing Payment for Area 2", UnitTypeId = 5 },
                new OrganizationUnit { Id = 36, ParentId = 17, Name = "Area Management for Area 1", UnitTypeId = 5 },
                new OrganizationUnit { Id = 37, ParentId = 17, Name = "Fleet Assets for Area 1", UnitTypeId = 5 },
                new OrganizationUnit { Id = 38, ParentId = 18, Name = "Area Management for Area 2", UnitTypeId = 5 },
                new OrganizationUnit { Id = 39, ParentId = 18, Name = "Fleet Assets for Area 2", UnitTypeId = 5 },
            };
            var jobFamilies = new []
            {
                new JobFamily { Id = 1, Name = "Director", Chief = true, Level = 1 },
                new JobFamily { Id = 2, Name = "Division", Chief = true, Level = 2 },
                new JobFamily { Id = 3, Name = "Department", Chief = true, Level = 3 },
                new JobFamily { Id = 4, Name = "Section", Chief = true, Level = 4 },
                new JobFamily { Id = 5, Name = "Officer", Chief = false, Level = 5 },
                new JobFamily { Id = 6, Name = "Staff", Chief = false, Level = 6 },
            };
            var jobs = new[]
            {
                new Job { Id = 1, JobFamilyId = 1, Name = "President Director" },
                new Job { Id = 2, JobFamilyId = 1, Name = "Director" },
                new Job { Id = 3, JobFamilyId = 2, Name = "Division Head" },
                new Job { Id = 4, JobFamilyId = 2, Name = "General Manager" },
                new Job { Id = 5, JobFamilyId = 3, Name = "Department Head" },
                new Job { Id = 6, JobFamilyId = 3, Name = "Manager" },
                new Job { Id = 7, JobFamilyId = 4, Name = "Section Head" },
                new Job { Id = 8, JobFamilyId = 4, Name = "Team Leader" },
                new Job { Id = 9, JobFamilyId = 5, Name = "Officer" },
                new Job { Id = 10, JobFamilyId = 6, Name = "Staff" },
            };
            var positions = new[]
            {
                new Position { Id = 1, OrganizationUnitId = 1, JobId = 1, Name = "President Director" },
                new Position { Id = 2, OrganizationUnitId = 2, JobId = 2, Name = "Marketing Director" },
                new Position { Id = 3, OrganizationUnitId = 3, JobId = 2, Name = "Finance&Logistic Director" },
                new Position { Id = 4, OrganizationUnitId = 4, JobId = 3, Name = "HR & GA Division Head" },
                new Position { Id = 5, OrganizationUnitId = 5, JobId = 3, Name = "IS Division Head" },
                new Position { Id = 6, OrganizationUnitId = 6, JobId = 4, Name = "After Sales General Manager" },
                new Position { Id = 7, OrganizationUnitId = 7, JobId = 4, Name = "Fleet Management General Manager" },
                new Position { Id = 8, OrganizationUnitId = 8, JobId = 4, Name = "Finance General Manager" },
                new Position { Id = 9, OrganizationUnitId = 9, JobId = 5, Name = "HR Operation Department Head" },
                new Position { Id = 10, OrganizationUnitId = 10, JobId = 5, Name = "General Affairs Department Head" },
                new Position { Id = 11, OrganizationUnitId = 11, JobId = 6, Name = "HR Method Manager" },
                new Position { Id = 12, OrganizationUnitId = 12, JobId = 5, Name = "System Development Department Head" },
                new Position { Id = 13, OrganizationUnitId = 13, JobId = 5, Name = "System Operation Department Head" },
                new Position { Id = 14, OrganizationUnitId = 14, JobId = 6, Name = "After Sales Manager" },
                new Position { Id = 15, OrganizationUnitId = 15, JobId = 6, Name = "Invoice Manager" },
                new Position { Id = 16, OrganizationUnitId = 16, JobId = 6, Name = "Incoming & Outgoing Payment Manager" },
                new Position { Id = 17, OrganizationUnitId = 17, JobId = 6, Name = "Fleet Area 1 Manager" },
                new Position { Id = 18, OrganizationUnitId = 18, JobId = 6, Name = "Fleet Area 2 Manager" },
                new Position { Id = 19, OrganizationUnitId = 19, JobId = 7, Name = "HR Business Partner Section Head" },
                new Position { Id = 20, OrganizationUnitId = 20, JobId = 7, Name = "HR Relations Section Head" },
                new Position { Id = 21, OrganizationUnitId = 21, JobId = 7, Name = "HR Training & Development Section Head" },
                new Position { Id = 22, OrganizationUnitId = 22, JobId = 7, Name = "HR Recruitment Section Head" },
                new Position { Id = 23, OrganizationUnitId = 23, JobId = 7, Name = "General Service Section Head" },
                new Position { Id = 24, OrganizationUnitId = 24, JobId = 7, Name = "GA Planning Section Head" },
                new Position { Id = 25, OrganizationUnitId = 25, JobId = 7, Name = "HR Information System Section Head" },
                new Position { Id = 26, OrganizationUnitId = 26, JobId = 7, Name = "HR Organization Section Head" },
                new Position { Id = 27, OrganizationUnitId = 27, JobId = 7, Name = "Application & Project Management Section Head" },
                new Position { Id = 28, OrganizationUnitId = 28, JobId = 7, Name = "Infrastructure Section Head" },
                new Position { Id = 29, OrganizationUnitId = 29, JobId = 7, Name = "Operation Section Head" },
                new Position { Id = 30, OrganizationUnitId = 30, JobId = 7, Name = "Parts Business Section Head" },
                new Position { Id = 31, OrganizationUnitId = 31, JobId = 7, Name = "Customer Service Section Head" },
                new Position { Id = 32, OrganizationUnitId = 32, JobId = 8, Name = "Invoice for Area 1 Team Leader" },
                new Position { Id = 33, OrganizationUnitId = 33, JobId = 8, Name = "Invoice for Area 2 Team Leader" },
                new Position { Id = 34, OrganizationUnitId = 34, JobId = 8, Name = "Incoming & Outgoing Payment for Area 1 Team Leader" },
                new Position { Id = 35, OrganizationUnitId = 35, JobId = 8, Name = "Incoming & Outgoing Payment for Area 2 Team Leader" },
                new Position { Id = 36, OrganizationUnitId = 36, JobId = 8, Name = "Area Management for Area 1 Team Leader" },
                new Position { Id = 37, OrganizationUnitId = 37, JobId = 8, Name = "Fleet Assets for Area 1 Team Leader" },
                new Position { Id = 38, OrganizationUnitId = 38, JobId = 8, Name = "Area Management for Area 2 Team Leader" },
                new Position { Id = 39, OrganizationUnitId = 39, JobId = 8, Name = "Fleet Assets for Area 2 Team Leader" },
                new Position { Id = 40, OrganizationUnitId = 19, JobId = 9, Name = "HR-BP Officer 1 for Area 1" },
                new Position { Id = 41, OrganizationUnitId = 19, JobId = 9, Name = "HR-BP Officer 2 for Area 1" },
                new Position { Id = 42, OrganizationUnitId = 19, JobId = 9, Name = "HR-BP Officer 1 for Area 2" },
                new Position { Id = 43, OrganizationUnitId = 19, JobId = 9, Name = "HR-BP Officer 2 for Area 2" },
                new Position { Id = 44, OrganizationUnitId = 20, JobId = 9, Name = "HR Relations Officer 1" },
                new Position { Id = 45, OrganizationUnitId = 20, JobId = 9, Name = "HR Relations Officer 2" },
                new Position { Id = 46, OrganizationUnitId = 20, JobId = 9, Name = "HR Relations Officer 3" },
                new Position { Id = 47, OrganizationUnitId = 21, JobId = 9, Name = "HR Training Officer 1" },
                new Position { Id = 48, OrganizationUnitId = 21, JobId = 9, Name = "HR Training Officer 2" },
                new Position { Id = 49, OrganizationUnitId = 21, JobId = 10, Name = "HR Training Staff 1" },
                new Position { Id = 50, OrganizationUnitId = 21, JobId = 10, Name = "HR Training Staff 2" },
                new Position { Id = 51, OrganizationUnitId = 22, JobId = 9, Name = "HR Recruitment Officer 1" },
                new Position { Id = 52, OrganizationUnitId = 22, JobId = 9, Name = "HR Recruitment Officer 2" },
                new Position { Id = 53, OrganizationUnitId = 22, JobId = 10, Name = "HR Recruitment Staff 1" },
                new Position { Id = 54, OrganizationUnitId = 22, JobId = 10, Name = "HR Recruitment Staff 2" },
                new Position { Id = 55, OrganizationUnitId = 23, JobId = 9, Name = "General Service Officer 1" },
                new Position { Id = 56, OrganizationUnitId = 23, JobId = 10, Name = "General Service Staff 1" },
                new Position { Id = 57, OrganizationUnitId = 24, JobId = 9, Name = "GA Planning Officer 1" },
                new Position { Id = 58, OrganizationUnitId = 24, JobId = 10, Name = "GA Planning Staff 1" },
                new Position { Id = 59, OrganizationUnitId = 24, JobId = 10, Name = "GA Planning Staff 2" },
                new Position { Id = 60, OrganizationUnitId = 25, JobId = 9, Name = "HRIS Officer 1" },
                new Position { Id = 61, OrganizationUnitId = 25, JobId = 10, Name = "HRIS Staff 1" },
                new Position { Id = 62, OrganizationUnitId = 25, JobId = 10, Name = "HRIS Staff 2" },
                new Position { Id = 63, OrganizationUnitId = 25, JobId = 10, Name = "HRIS Staff 3" },
                new Position { Id = 64, OrganizationUnitId = 25, JobId = 10, Name = "HRIS Staff 4" },
                new Position { Id = 65, OrganizationUnitId = 26, JobId = 9, Name = "HR Organization Officer 1" },
                new Position { Id = 66, OrganizationUnitId = 26, JobId = 9, Name = "HR Organization Officer 2" },
                new Position { Id = 67, OrganizationUnitId = 27, JobId = 9, Name = "Project Management Officer 1" },
                new Position { Id = 68, OrganizationUnitId = 27, JobId = 9, Name = "Project Management Officer 2" },
                new Position { Id = 69, OrganizationUnitId = 28, JobId = 9, Name = "Infrastructure Officer 1" },
                new Position { Id = 70, OrganizationUnitId = 28, JobId = 10, Name = "Infrastructure Staff 1" },
                new Position { Id = 71, OrganizationUnitId = 29, JobId = 9, Name = "Operation Officer 1" },
                new Position { Id = 72, OrganizationUnitId = 29, JobId = 10, Name = "Operation Staff 1" },
                new Position { Id = 73, OrganizationUnitId = 29, JobId = 10, Name = "Operation Staff 2" },
                new Position { Id = 74, OrganizationUnitId = 30, JobId = 9, Name = "Part Business Officer 1" },
                new Position { Id = 75, OrganizationUnitId = 30, JobId = 10, Name = "Part Business Staff 2" },
                new Position { Id = 76, OrganizationUnitId = 31, JobId = 10, Name = "Customer Service Staff 1" },
                new Position { Id = 77, OrganizationUnitId = 31, JobId = 10, Name = "Customer Service Staff 2" },
                new Position { Id = 78, OrganizationUnitId = 31, JobId = 10, Name = "Customer Service Staff 3" },
                new Position { Id = 79, OrganizationUnitId = 31, JobId = 10, Name = "Customer Service Staff 4" },
                new Position { Id = 80, OrganizationUnitId = 32, JobId = 10, Name = "Invoice for Area 1 Staff 1" },
                new Position { Id = 81, OrganizationUnitId = 32, JobId = 10, Name = "Invoice for Area 1 Staff 2" },
                new Position { Id = 82, OrganizationUnitId = 33, JobId = 10, Name = "Invoice for Area 2 Staff 1" },
                new Position { Id = 83, OrganizationUnitId = 33, JobId = 10, Name = "Invoice for Area 2 Staff 2" },
                new Position { Id = 84, OrganizationUnitId = 34, JobId = 10, Name = "Incoming & Outgoing Payment for Area 1 Staff 1" },
                new Position { Id = 85, OrganizationUnitId = 34, JobId = 10, Name = "Incoming & Outgoing Payment for Area 1 Staff 2" },
                new Position { Id = 86, OrganizationUnitId = 35, JobId = 10, Name = "Incoming & Outgoing Payment for Area 2 Staff 1" },
                new Position { Id = 87, OrganizationUnitId = 35, JobId = 10, Name = "Incoming & Outgoing Payment for Area 2 Staff 2" },
                new Position { Id = 88, OrganizationUnitId = 36, JobId = 10, Name = "Area Management for Area 1 Staff 1" },
                new Position { Id = 89, OrganizationUnitId = 36, JobId = 10, Name = "Area Management for Area 1 Staff 2" },
                new Position { Id = 90, OrganizationUnitId = 36, JobId = 10, Name = "Area Management for Area 1 Staff 3" },
                new Position { Id = 91, OrganizationUnitId = 37, JobId = 10, Name = "Fleet Assets for Area 1 Staff 1" },
                new Position { Id = 92, OrganizationUnitId = 37, JobId = 10, Name = "Fleet Assets for Area 1 Staff 2" },
                new Position { Id = 93, OrganizationUnitId = 38, JobId = 10, Name = "Area Management for Area 2 Staff 1" },
                new Position { Id = 94, OrganizationUnitId = 38, JobId = 10, Name = "Area Management for Area 2 Staff 2" },
                new Position { Id = 95, OrganizationUnitId = 38, JobId = 10, Name = "Area Management for Area 2 Staff 3" },
                new Position { Id = 96, OrganizationUnitId = 39, JobId = 10, Name = "Fleet Assets for Area 2 Staff 1" },
                new Position { Id = 97, OrganizationUnitId = 39, JobId = 10, Name = "Fleet Assets for Area 2 Staff 2" },
            };
            var employees = new[]
            {
                new Employee { Id = 1, Nik = "10-1048988", Name = "Mel Gayler", Email = "mgayler0@pbs.org", Gender = Gender.Female },
                new Employee { Id = 2, Nik = "47-1762145", Name = "Jamesy Creighton", Email = "jcreighton1@narod.ru", Gender = Gender.Female },
                new Employee { Id = 3, Nik = "37-8223839", Name = "Darby Battison", Email = "dbattison2@time.com", Gender = Gender.Male },
                new Employee { Id = 4, Nik = "91-0314087", Name = "Jody Nend", Email = "jnend3@forbes.com", Gender = Gender.Male },
                new Employee { Id = 5, Nik = "28-9419352", Name = "Elia Scoates", Email = "escoates4@icio.us", Gender = Gender.Female },
                new Employee { Id = 6, Nik = "16-3055176", Name = "Jess Bohey", Email = "jbohey5@devhub.com", Gender = Gender.Male },
                new Employee { Id = 7, Nik = "61-6085095", Name = "Daryn Halsey", Email = "dhalsey6@nyu.edu", Gender = Gender.Male },
                new Employee { Id = 8, Nik = "24-6101885", Name = "Bernardine Kiss", Email = "bkiss7@privacy.gov.au", Gender = Gender.Female },
                new Employee { Id = 9, Nik = "71-3567419", Name = "Nissy MacCaffrey", Email = "nmaccaffrey8@reddit.com", Gender = Gender.Female },
                new Employee { Id = 10, Nik = "62-0113734", Name = "Erek Beddon", Email = "ebeddon9@netscape.com", Gender = Gender.Male },
                new Employee { Id = 11, Nik = "72-6412363", Name = "Ted Cownden", Email = "tcowndena@cpanel.net", Gender = Gender.Male },
                new Employee { Id = 12, Nik = "24-4413792", Name = "Ashton Skate", Email = "askateb@google.cn", Gender = Gender.Female },
                new Employee { Id = 13, Nik = "60-4658258", Name = "Lanna Collicott", Email = "lcollicottc@nbcnews.com", Gender = Gender.Female },
                new Employee { Id = 14, Nik = "34-9826673", Name = "Catherine Howbrook", Email = "chowbrookd@sfgate.com", Gender = Gender.Male },
                new Employee { Id = 15, Nik = "88-2216204", Name = "Orelie Brambley", Email = "obrambleye@go.com", Gender = Gender.Female },
                new Employee { Id = 16, Nik = "18-8279452", Name = "Suki Sketchley", Email = "ssketchleyf@deviantart.com", Gender = Gender.Male },
                new Employee { Id = 17, Nik = "39-3254805", Name = "Mark Schuck", Email = "mschuckg@craigslist.org", Gender = Gender.Female },
                new Employee { Id = 18, Nik = "37-6112028", Name = "Carlo Legh", Email = "cleghh@shop-pro.jp", Gender = Gender.Female },
                new Employee { Id = 19, Nik = "96-5553044", Name = "Francene Iltchev", Email = "filtchevi@epa.gov", Gender = Gender.Female },
                new Employee { Id = 20, Nik = "69-2359616", Name = "Lonni Dendle", Email = "ldendlej@businessinsider.com", Gender = Gender.Female },
                new Employee { Id = 21, Nik = "82-0383707", Name = "Bliss Belsher", Email = "bbelsherk@foxnews.com", Gender = Gender.Female },
                new Employee { Id = 22, Nik = "72-9952744", Name = "Ferdinande MacMaykin", Email = "fmacmaykinl@etsy.com", Gender = Gender.Male },
                new Employee { Id = 23, Nik = "48-2818938", Name = "Zulema O'Donegan", Email = "zodoneganm@cdbaby.com", Gender = Gender.Male },
                new Employee { Id = 24, Nik = "86-1595893", Name = "Alistair Blampey", Email = "ablampeyn@theglobeandmail.com", Gender = Gender.Male },
                new Employee { Id = 25, Nik = "23-3068463", Name = "Andrei Risso", Email = "arissoo@bloglines.com", Gender = Gender.Male },
                new Employee { Id = 26, Nik = "69-0210634", Name = "Jamison Allon", Email = "jallonp@tripod.com", Gender = Gender.Male },
                new Employee { Id = 27, Nik = "82-2992571", Name = "Zea Callcott", Email = "zcallcottq@army.mil", Gender = Gender.Female },
                new Employee { Id = 28, Nik = "54-2224031", Name = "Lorrie McIlwrick", Email = "lmcilwrickr@omniture.com", Gender = Gender.Male },
                new Employee { Id = 29, Nik = "56-2525746", Name = "Zola MacIver", Email = "zmacivers@blogs.com", Gender = Gender.Male },
                new Employee { Id = 30, Nik = "94-5064654", Name = "Nicolas Boys", Email = "nboyst@go.com", Gender = Gender.Female },
                new Employee { Id = 31, Nik = "20-0489711", Name = "Ahmed Killiam", Email = "akilliamu@mlb.com", Gender = Gender.Female },
                new Employee { Id = 32, Nik = "78-5548426", Name = "Cornell Krammer", Email = "ckrammerv@sun.com", Gender = Gender.Female },
                new Employee { Id = 33, Nik = "72-1763903", Name = "Hildagard Lavin", Email = "hlavinw@foxnews.com", Gender = Gender.Male },
                new Employee { Id = 34, Nik = "44-8503430", Name = "Roberto Kimber", Email = "rkimberx@gov.uk", Gender = Gender.Male },
                new Employee { Id = 35, Nik = "08-2116563", Name = "Martino Lowery", Email = "mloweryy@dell.com", Gender = Gender.Female },
                new Employee { Id = 36, Nik = "87-6922578", Name = "Merrel Ziemen", Email = "mziemenz@utexas.edu", Gender = Gender.Female },
                new Employee { Id = 37, Nik = "97-3218150", Name = "Jerrome Douch", Email = "jdouch10@va.gov", Gender = Gender.Female },
                new Employee { Id = 38, Nik = "85-0490847", Name = "Kristal Mingey", Email = "kmingey11@walmart.com", Gender = Gender.Male },
                new Employee { Id = 39, Nik = "94-6780123", Name = "Cher Duny", Email = "cduny12@istockphoto.com", Gender = Gender.Male },
                new Employee { Id = 40, Nik = "63-0929091", Name = "Collie Ruberti", Email = "cruberti13@wufoo.com", Gender = Gender.Female },
                new Employee { Id = 41, Nik = "34-5293506", Name = "Perrine Lere", Email = "plere14@naver.com", Gender = Gender.Male },
                new Employee { Id = 42, Nik = "91-3348766", Name = "Field Finlaison", Email = "ffinlaison15@dagondesign.com", Gender = Gender.Male },
                new Employee { Id = 43, Nik = "19-7455605", Name = "Adara Brisse", Email = "abrisse16@behance.net", Gender = Gender.Female },
                new Employee { Id = 44, Nik = "29-0418039", Name = "Correy Edgcumbe", Email = "cedgcumbe17@loc.gov", Gender = Gender.Female },
                new Employee { Id = 45, Nik = "38-7149955", Name = "Mira Whinney", Email = "mwhinney18@bbc.co.uk", Gender = Gender.Female },
                new Employee { Id = 46, Nik = "90-5505102", Name = "Jonell Dove", Email = "jdove19@boston.com", Gender = Gender.Male },
                new Employee { Id = 47, Nik = "79-0343240", Name = "Teddie Trays", Email = "ttrays1a@nytimes.com", Gender = Gender.Female },
                new Employee { Id = 48, Nik = "50-6357879", Name = "Farrand Nise", Email = "fnise1b@eventbrite.com", Gender = Gender.Male },
                new Employee { Id = 49, Nik = "41-2243010", Name = "Helenka Mansford", Email = "hmansford1c@google.pl", Gender = Gender.Female },
                new Employee { Id = 50, Nik = "02-0815622", Name = "Brigitta Schulz", Email = "bschulz1d@dion.ne.jp", Gender = Gender.Male },
                new Employee { Id = 51, Nik = "38-2939731", Name = "Skip Sherwood", Email = "ssherwood1e@chronoengine.com", Gender = Gender.Female },
                new Employee { Id = 52, Nik = "08-4654914", Name = "Felix Ocklin", Email = "focklin1f@360.cn", Gender = Gender.Male },
                new Employee { Id = 53, Nik = "18-8004793", Name = "Carmelia Ferrarin", Email = "cferrarin1g@blogs.com", Gender = Gender.Female },
                new Employee { Id = 54, Nik = "17-7498813", Name = "Hedwiga Ethington", Email = "hethington1h@joomla.org", Gender = Gender.Female },
                new Employee { Id = 55, Nik = "92-4214889", Name = "Demetris Weagener", Email = "dweagener1i@wsj.com", Gender = Gender.Female },
                new Employee { Id = 56, Nik = "93-4927134", Name = "Cheslie Girardengo", Email = "cgirardengo1j@mozilla.com", Gender = Gender.Male },
                new Employee { Id = 57, Nik = "15-0984589", Name = "Hazel Greatbach", Email = "hgreatbach1k@arstechnica.com", Gender = Gender.Male },
                new Employee { Id = 58, Nik = "27-0052360", Name = "Nicko Gaul", Email = "ngaul1l@addthis.com", Gender = Gender.Female },
                new Employee { Id = 59, Nik = "83-7081455", Name = "Virgil Rolfini", Email = "vrolfini1m@webeden.co.uk", Gender = Gender.Female },
                new Employee { Id = 60, Nik = "37-2705221", Name = "Fabe Samwayes", Email = "fsamwayes1n@wordpress.com", Gender = Gender.Female },
                new Employee { Id = 61, Nik = "49-8508476", Name = "Kirstin Drever", Email = "kdrever1o@amazon.co.jp", Gender = Gender.Male },
                new Employee { Id = 62, Nik = "16-8960074", Name = "Delcine Frisch", Email = "dfrisch1p@noaa.gov", Gender = Gender.Female },
                new Employee { Id = 63, Nik = "03-7443619", Name = "Desiree Butterwick", Email = "dbutterwick1q@mapquest.com", Gender = Gender.Male },
                new Employee { Id = 64, Nik = "18-0221690", Name = "Vladimir Glassford", Email = "vglassford1r@wordpress.org", Gender = Gender.Female },
                new Employee { Id = 65, Nik = "47-6749242", Name = "Cirillo Greenfield", Email = "cgreenfield1s@simplemachines.org", Gender = Gender.Male },
                new Employee { Id = 66, Nik = "52-1445017", Name = "Tally Bridgeman", Email = "tbridgeman1t@is.gd", Gender = Gender.Female },
                new Employee { Id = 67, Nik = "22-1746400", Name = "Gwendolyn MacMaykin", Email = "gmacmaykin1u@cloudflare.com", Gender = Gender.Female },
                new Employee { Id = 68, Nik = "06-5995495", Name = "Stanford Ragsdall", Email = "sragsdall1v@dedecms.com", Gender = Gender.Male },
                new Employee { Id = 69, Nik = "11-7048962", Name = "Husein Sterrick", Email = "hsterrick1w@feedburner.com", Gender = Gender.Male },
                new Employee { Id = 70, Nik = "70-6420358", Name = "Vincents Armfirld", Email = "varmfirld1x@google.co.jp", Gender = Gender.Female },
                new Employee { Id = 71, Nik = "41-5898580", Name = "Liliane Lambertini", Email = "llambertini1y@blog.com", Gender = Gender.Female },
                new Employee { Id = 72, Nik = "27-6647619", Name = "Livvie Gooderham", Email = "lgooderham1z@mashable.com", Gender = Gender.Female },
                new Employee { Id = 73, Nik = "93-6382280", Name = "Ari Pigeram", Email = "apigeram20@omniture.com", Gender = Gender.Male },
                new Employee { Id = 74, Nik = "75-6262997", Name = "Angus Assard", Email = "aassard21@foxnews.com", Gender = Gender.Male },
                new Employee { Id = 75, Nik = "22-7025394", Name = "Eamon Carradice", Email = "ecarradice22@booking.com", Gender = Gender.Female },
                new Employee { Id = 76, Nik = "70-2070824", Name = "Baron Outerbridge", Email = "bouterbridge23@so-net.ne.jp", Gender = Gender.Male },
                new Employee { Id = 77, Nik = "77-2671821", Name = "Claudian Zywicki", Email = "czywicki24@cloudflare.com", Gender = Gender.Female },
                new Employee { Id = 78, Nik = "90-7273384", Name = "Ethelin Trubshaw", Email = "etrubshaw25@elegantthemes.com", Gender = Gender.Female },
                new Employee { Id = 79, Nik = "40-6749073", Name = "Gabriel Creane", Email = "gcreane26@soundcloud.com", Gender = Gender.Male },
                new Employee { Id = 80, Nik = "23-5605008", Name = "Ailene Rablin", Email = "arablin27@sbwire.com", Gender = Gender.Male },
                new Employee { Id = 81, Nik = "76-5328956", Name = "Katherina Tidcomb", Email = "ktidcomb28@baidu.com", Gender = Gender.Male },
                new Employee { Id = 82, Nik = "96-7156792", Name = "Lorri Vanyushkin", Email = "lvanyushkin29@typepad.com", Gender = Gender.Male },
                new Employee { Id = 83, Nik = "26-4753492", Name = "Sigvard Boulton", Email = "sboulton2a@google.fr", Gender = Gender.Female },
                new Employee { Id = 84, Nik = "33-2731305", Name = "Ashli Scandrite", Email = "ascandrite2b@hao123.com", Gender = Gender.Male },
                new Employee { Id = 85, Nik = "47-9019316", Name = "Ellyn Kearley", Email = "ekearley2c@yelp.com", Gender = Gender.Female },
                new Employee { Id = 86, Nik = "44-5884794", Name = "Joyann Brodley", Email = "jbrodley2d@istockphoto.com", Gender = Gender.Female },
                new Employee { Id = 87, Nik = "35-4832301", Name = "Nanny Welsby", Email = "nwelsby2e@blog.com", Gender = Gender.Male },
                new Employee { Id = 88, Nik = "81-6395172", Name = "Nada Tyre", Email = "ntyre2f@theguardian.com", Gender = Gender.Male },
                new Employee { Id = 89, Nik = "22-0179139", Name = "Oren Costard", Email = "ocostard2g@seattletimes.com", Gender = Gender.Male },
                new Employee { Id = 90, Nik = "47-6005836", Name = "Travers Biermatowicz", Email = "tbiermatowicz2h@fotki.com", Gender = Gender.Female },
                new Employee { Id = 91, Nik = "14-4571557", Name = "Sophia Dyka", Email = "sdyka2i@msu.edu", Gender = Gender.Male },
                new Employee { Id = 92, Nik = "07-9191238", Name = "Briney Esparza", Email = "besparza2j@cmu.edu", Gender = Gender.Female },
                new Employee { Id = 93, Nik = "14-1446030", Name = "Oren Palphramand", Email = "opalphramand2k@house.gov", Gender = Gender.Female },
                new Employee { Id = 94, Nik = "94-7550392", Name = "Iggie Sarchwell", Email = "isarchwell2l@jimdo.com", Gender = Gender.Male },
                new Employee { Id = 95, Nik = "33-6646019", Name = "Marena Skiplorne", Email = "mskiplorne2m@usnews.com", Gender = Gender.Male },
                new Employee { Id = 96, Nik = "48-3081084", Name = "Donnie Colebeck", Email = "dcolebeck2n@google.co.jp", Gender = Gender.Female },
                new Employee { Id = 97, Nik = "48-9978999", Name = "Clea Creed", Email = "ccreed2o@umich.edu", Gender = Gender.Male },
            };
            var employeePositions = new[]
            {
                new EmployeePosition { Id = 1, EmployeeId = 1, PositionId = 1, Staffing = 100 },
                new EmployeePosition { Id = 2, EmployeeId = 2, PositionId = 2, Staffing = 100 },
                new EmployeePosition { Id = 3, EmployeeId = 3, PositionId = 3, Staffing = 100 },
                new EmployeePosition { Id = 4, EmployeeId = 4, PositionId = 4, Staffing = 100 },
                new EmployeePosition { Id = 5, EmployeeId = 5, PositionId = 5, Staffing = 100 },
                new EmployeePosition { Id = 6, EmployeeId = 6, PositionId = 6, Staffing = 100 },
                new EmployeePosition { Id = 7, EmployeeId = 7, PositionId = 7, Staffing = 100 },
                new EmployeePosition { Id = 8, EmployeeId = 8, PositionId = 8, Staffing = 100 },
                new EmployeePosition { Id = 9, EmployeeId = 9, PositionId = 9, Staffing = 100 },
                new EmployeePosition { Id = 10, EmployeeId = 10, PositionId = 10, Staffing = 100 },
                new EmployeePosition { Id = 11, EmployeeId = 11, PositionId = 11, Staffing = 100 },
                new EmployeePosition { Id = 12, EmployeeId = 12, PositionId = 12, Staffing = 100 },
                new EmployeePosition { Id = 13, EmployeeId = 13, PositionId = 13, Staffing = 100 },
                new EmployeePosition { Id = 14, EmployeeId = 14, PositionId = 14, Staffing = 100 },
                new EmployeePosition { Id = 15, EmployeeId = 15, PositionId = 15, Staffing = 100 },
                new EmployeePosition { Id = 16, EmployeeId = 16, PositionId = 16, Staffing = 100 },
                new EmployeePosition { Id = 17, EmployeeId = 17, PositionId = 17, Staffing = 100 },
                new EmployeePosition { Id = 18, EmployeeId = 18, PositionId = 18, Staffing = 100 },
                new EmployeePosition { Id = 19, EmployeeId = 19, PositionId = 19, Staffing = 100 },
                new EmployeePosition { Id = 20, EmployeeId = 20, PositionId = 20, Staffing = 100 },
                new EmployeePosition { Id = 21, EmployeeId = 21, PositionId = 21, Staffing = 100 },
                new EmployeePosition { Id = 22, EmployeeId = 22, PositionId = 22, Staffing = 100 },
                new EmployeePosition { Id = 23, EmployeeId = 23, PositionId = 23, Staffing = 100 },
                new EmployeePosition { Id = 24, EmployeeId = 24, PositionId = 24, Staffing = 100 },
                new EmployeePosition { Id = 25, EmployeeId = 25, PositionId = 25, Staffing = 100 },
                new EmployeePosition { Id = 26, EmployeeId = 26, PositionId = 26, Staffing = 100 },
                new EmployeePosition { Id = 27, EmployeeId = 27, PositionId = 27, Staffing = 100 },
                new EmployeePosition { Id = 28, EmployeeId = 28, PositionId = 28, Staffing = 100 },
                new EmployeePosition { Id = 29, EmployeeId = 29, PositionId = 29, Staffing = 100 },
                new EmployeePosition { Id = 30, EmployeeId = 30, PositionId = 30, Staffing = 100 },
                new EmployeePosition { Id = 31, EmployeeId = 31, PositionId = 31, Staffing = 100 },
                new EmployeePosition { Id = 32, EmployeeId = 32, PositionId = 32, Staffing = 100 },
                new EmployeePosition { Id = 33, EmployeeId = 33, PositionId = 33, Staffing = 100 },
                new EmployeePosition { Id = 34, EmployeeId = 34, PositionId = 34, Staffing = 100 },
                new EmployeePosition { Id = 35, EmployeeId = 35, PositionId = 35, Staffing = 100 },
                new EmployeePosition { Id = 36, EmployeeId = 36, PositionId = 36, Staffing = 100 },
                new EmployeePosition { Id = 37, EmployeeId = 37, PositionId = 37, Staffing = 100 },
                new EmployeePosition { Id = 38, EmployeeId = 38, PositionId = 38, Staffing = 100 },
                new EmployeePosition { Id = 39, EmployeeId = 39, PositionId = 39, Staffing = 100 },
                new EmployeePosition { Id = 40, EmployeeId = 40, PositionId = 40, Staffing = 100 },
                new EmployeePosition { Id = 41, EmployeeId = 41, PositionId = 41, Staffing = 100 },
                new EmployeePosition { Id = 42, EmployeeId = 42, PositionId = 42, Staffing = 100 },
                new EmployeePosition { Id = 43, EmployeeId = 43, PositionId = 43, Staffing = 100 },
                new EmployeePosition { Id = 44, EmployeeId = 44, PositionId = 44, Staffing = 100 },
                new EmployeePosition { Id = 45, EmployeeId = 45, PositionId = 45, Staffing = 100 },
                new EmployeePosition { Id = 46, EmployeeId = 46, PositionId = 46, Staffing = 100 },
                new EmployeePosition { Id = 47, EmployeeId = 47, PositionId = 47, Staffing = 100 },
                new EmployeePosition { Id = 48, EmployeeId = 48, PositionId = 48, Staffing = 100 },
                new EmployeePosition { Id = 49, EmployeeId = 49, PositionId = 49, Staffing = 100 },
                new EmployeePosition { Id = 50, EmployeeId = 50, PositionId = 50, Staffing = 100 },
                new EmployeePosition { Id = 51, EmployeeId = 51, PositionId = 51, Staffing = 100 },
                new EmployeePosition { Id = 52, EmployeeId = 52, PositionId = 52, Staffing = 100 },
                new EmployeePosition { Id = 53, EmployeeId = 53, PositionId = 53, Staffing = 100 },
                new EmployeePosition { Id = 54, EmployeeId = 54, PositionId = 54, Staffing = 100 },
                new EmployeePosition { Id = 55, EmployeeId = 55, PositionId = 55, Staffing = 100 },
                new EmployeePosition { Id = 56, EmployeeId = 56, PositionId = 56, Staffing = 100 },
                new EmployeePosition { Id = 57, EmployeeId = 57, PositionId = 57, Staffing = 100 },
                new EmployeePosition { Id = 58, EmployeeId = 58, PositionId = 58, Staffing = 100 },
                new EmployeePosition { Id = 59, EmployeeId = 59, PositionId = 59, Staffing = 100 },
                new EmployeePosition { Id = 60, EmployeeId = 60, PositionId = 60, Staffing = 100 },
                new EmployeePosition { Id = 61, EmployeeId = 61, PositionId = 61, Staffing = 100 },
                new EmployeePosition { Id = 62, EmployeeId = 62, PositionId = 62, Staffing = 100 },
                new EmployeePosition { Id = 63, EmployeeId = 63, PositionId = 63, Staffing = 100 },
                new EmployeePosition { Id = 64, EmployeeId = 64, PositionId = 64, Staffing = 100 },
                new EmployeePosition { Id = 65, EmployeeId = 65, PositionId = 65, Staffing = 100 },
                new EmployeePosition { Id = 66, EmployeeId = 66, PositionId = 66, Staffing = 100 },
                new EmployeePosition { Id = 67, EmployeeId = 67, PositionId = 67, Staffing = 100 },
                new EmployeePosition { Id = 68, EmployeeId = 68, PositionId = 68, Staffing = 100 },
                new EmployeePosition { Id = 69, EmployeeId = 69, PositionId = 69, Staffing = 100 },
                new EmployeePosition { Id = 70, EmployeeId = 70, PositionId = 70, Staffing = 100 },
                new EmployeePosition { Id = 71, EmployeeId = 71, PositionId = 71, Staffing = 100 },
                new EmployeePosition { Id = 72, EmployeeId = 72, PositionId = 72, Staffing = 100 },
                new EmployeePosition { Id = 73, EmployeeId = 73, PositionId = 73, Staffing = 100 },
                new EmployeePosition { Id = 74, EmployeeId = 74, PositionId = 74, Staffing = 100 },
                new EmployeePosition { Id = 75, EmployeeId = 75, PositionId = 75, Staffing = 100 },
                new EmployeePosition { Id = 76, EmployeeId = 76, PositionId = 76, Staffing = 100 },
                new EmployeePosition { Id = 77, EmployeeId = 77, PositionId = 77, Staffing = 100 },
                new EmployeePosition { Id = 78, EmployeeId = 78, PositionId = 78, Staffing = 100 },
                new EmployeePosition { Id = 79, EmployeeId = 79, PositionId = 79, Staffing = 100 },
                new EmployeePosition { Id = 80, EmployeeId = 80, PositionId = 80, Staffing = 100 },
                new EmployeePosition { Id = 81, EmployeeId = 81, PositionId = 81, Staffing = 100 },
                new EmployeePosition { Id = 82, EmployeeId = 82, PositionId = 82, Staffing = 100 },
                new EmployeePosition { Id = 83, EmployeeId = 83, PositionId = 83, Staffing = 100 },
                new EmployeePosition { Id = 84, EmployeeId = 84, PositionId = 84, Staffing = 100 },
                new EmployeePosition { Id = 85, EmployeeId = 85, PositionId = 85, Staffing = 100 },
                new EmployeePosition { Id = 86, EmployeeId = 86, PositionId = 86, Staffing = 100 },
                new EmployeePosition { Id = 87, EmployeeId = 87, PositionId = 87, Staffing = 100 },
                new EmployeePosition { Id = 88, EmployeeId = 88, PositionId = 88, Staffing = 100 },
                new EmployeePosition { Id = 89, EmployeeId = 89, PositionId = 89, Staffing = 100 },
                new EmployeePosition { Id = 90, EmployeeId = 90, PositionId = 90, Staffing = 100 },
                new EmployeePosition { Id = 91, EmployeeId = 91, PositionId = 91, Staffing = 100 },
                new EmployeePosition { Id = 92, EmployeeId = 92, PositionId = 92, Staffing = 100 },
                new EmployeePosition { Id = 93, EmployeeId = 93, PositionId = 93, Staffing = 100 },
                new EmployeePosition { Id = 94, EmployeeId = 94, PositionId = 94, Staffing = 100 },
                new EmployeePosition { Id = 95, EmployeeId = 95, PositionId = 95, Staffing = 100 },
                new EmployeePosition { Id = 96, EmployeeId = 96, PositionId = 96, Staffing = 100 },
                new EmployeePosition { Id = 97, EmployeeId = 97, PositionId = 97, Staffing = 100 },
            };

            using var transaction = context.Database.BeginTransaction();
            await context.SafeAddRangeAsync(unitTypes);
            await context.SafeAddRangeAsync(organizationUnits);
            await context.SafeAddRangeAsync(jobFamilies);
            await context.SafeAddRangeAsync(jobs);
            await context.SafeAddRangeAsync(positions);
            await context.SafeAddRangeAsync(employees);
            await context.SafeAddRangeAsync(employeePositions);

            transaction.Commit();
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }
    }
}
